version: '3'
networks:
  vlan01:
    attachable: true
    driver: bridge
  nginx-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
services:
  db01:
    image: ${database_hostname}-postgres
    build:
      context: db/
      dockerfile: Dockerfile
    hostname: ${database_hostname}
    ports:
      - "${database_port}"
    environment:
      - POSTGRES_USER=${database_username}
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}
    env_file:
      - .env
    volumes:
      - data:/data/db
    networks:
      - ${net_name}
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        placement:
          constraints:
            - node.labels.fastapi.db01 == true
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:${database_port}"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
  server01:
    image: ${service_host}-fastapi
    build:
      context: server/
      dockerfile: Dockerfile
    hostname: ${service_host}
    working_dir: /fastapi
    volumes:
      - ./requirements.txt:/fastapi/requirements.txt
      - .:/fastapi/
    ports:
      - "${service_port}"
    environment:
      - database_hostname=${database_hostname}
      - database_port=${database_port}
      - database_password=${database_password}
      - database_name=${database_name}
      - database_username=${database_username}
      - secret_key=${secret_key}
      - algorithm=${algorithm}
      - access_token_expire_minutes=${access_token_expire_minutes}
      - service_port=${service_port}
      - net_name=${net_name}
      - service_host=${service_host}
    env_file:
      - .env
    networks:
      - ${net_name}
    depends_on:
      - ${database_hostname}
    command:
      - bash
      - -c
      - |
        apt update
        pip install --upgrade pip
        pip install virtualenv
        virtualenv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        export PORT=$${PORT:-8000}
        echo "Running on port $$PORT"
        uvicorn app.main:app --host localhost --port $$PORT
      # $PORT is automatically set by docker when the container is started
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        placement:
          constraints:
            - node.labels.fastapi.server01 == true
  api_worker01:
    image: ${api_worker}-alpine
    build:
      context: api_worker/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - create_user_json=${create_user_json}
      - samplepass=${samplepass}
      - samplepost=${samplepost}
      - sampleuser=${sampleuser}
      - service_host=${service_host}
      - service_port=${service_port}
      - net_name=${net_name}
      - api_worker=${api_worker}
    env_file:
      - .env
    networks:
      - ${net_name}
    depends_on:
      - ${service_host}
    command:
      - sh
      - -c
      - |
        apk update
        apk upgrade
        apk add sed curl
        apk add jq
        until curl -L -H "Content-Type: application/json" -X POST -d '${create_user_json}' http://${service_host}:${service_port}/users; do sleep 1; done &&
        RESPO=$$(curl -L -X POST -d "username=${sampleuser}&password=${samplepass}" http://${service_host}:${service_port}/login)&&
        ACCESS=$$(echo $$RESPO | jq -r '.access_token')&&
        until curl -L -X POST http://${service_host}:${service_port}/posts -H "Authorization: Bearer $$ACCESS" -H "Content-Type: application/json" -d '${samplepost}'; do sleep 1; done
    deploy:
      replicas: 1
      # update_config:
      #   failure_action: rollback
      #placement:
      #constraints:
      #- node.labels.fastapi.api_worker01 == true
  nginx01:
    image: ${nginx_host}-nginx
    hostname: ${nginx_host}
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "${nginx_port}:${nginx_port}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - service_host=${service_host}
      - service_port=${service_port}
      - net_name=${net_name}
      - api_worker=${api_worker}
      - nginx_port=${nginx_port}
      - nginx_host=${nginx_host}
    env_file:
      - .env
    depends_on:
      - ${service_host}
      - ${api_worker}
    networks:
      nginx-net:
        - ipv4_address: 192.168.1.66
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:${service_port}/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      # update_config:
      #   failure_action: rollback
      #placement:
      #constraints:
      #- node.labels.fastapi.api_worker01 == true
volumes:
  data:
