FROM python:3.10

# Set environment variables
# ENV database_hostname=db01 \
#     database_port=5432 \
#     database_password= \
#     database_name= \
#     database_username= \
#     secret_key= \
#     algorithm= \
#     access_token_expire_minutes=

# Set the working directory
# WORKDIR /fastapi

# EXPOSE 8000

# ADD requirements.txt ./

# Install dependencies
#RUN pip install --upgrade pip && pip install -r requirements.txt && apt update

# COPY . .

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]